name: Publish Docker image 

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Install dependencies
        run: npm install
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: kajalmahto1318/Node-JS-APP

          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Send success email
        if: success()
        run: |
          node sendSuccessEmail.js \
            --to=mahtokajal765@gmail.com \
            --from=kajalmahato.techanek@gmail.com \
            --subject="SUCCESS: ${{ github.job }} job of ${{ github.repository }} has succeeded" \
            --body="The ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has succeeded. Commit: ${{ github.sha }} Branch: ${{ github.ref }}" \
            --priority=high --convert_markdown=true

      - name: Send failure email
        if: failure()
        run: |
          node sendSuccessEmail.js \
            --to=mahtokajal765@gmail.com \
            --from=kajalmahato.techanek@gmail.com \
            --subject="FAILURE: ${{ github.job }} job of ${{ github.repository }} has failed" \
            --body="The ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has failed. Commit: ${{ github.sha }} Branch: ${{ github.ref }}" \
            --priority=high --convert_markdown=true  




          
       
